# Generated by Django 3.0.7 on 2023-06-12 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arena', '0003_auto_20230612_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(null=True)),
                ('pre_pay', models.FloatField(default=0)),
                ('pay', models.FloatField(default=0)),
                ('back_pay', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arena.Arena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_pay', models.FloatField(default=0)),
                ('full_pay', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Bron')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
